# -*- coding: utf-8 -*-
"""Dfault data generation for two stocks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1_HZdcA4w0EI35pvcctmoMga91FvUwE
"""

import yfinance as yf
import pandas as pd
# Define the ticker symbols for the stocks
tickers = ['AAPL', 'GOOGL']
# Define the date range
start_date = '2019-01-01'
end_date = '2023-12-31'
# Download the historical data
data = yf.download(tickers, start=start_date, end=end_date)['Adj Close']
# Save the combined data to a single CSV file
data.to_csv('combined_historical_data.csv')
print("Data download complete.")